<#
.SYNOPSIS
Generate a snapshot `spec_filled.md` from `spec.md` with a timestamped header.

.DESCRIPTION
This script reads `spec.md` from the provided feature directory and writes
`spec_filled.md` with a generated header that identifies the generator and timestamp.

.PARAMETER FeatureDir
Path to the feature folder containing `spec.md`. Defaults to `specs/001-modern-powerups-pacman` in repository root.

.EXAMPLE
# From repo root:
# PowerShell
# & .\.specify\scripts\powershell\generate-spec-filled.ps1

# Or explicitly:
# & .\.specify\scripts\powershell\generate-spec-filled.ps1 -FeatureDir "specs\001-modern-powerups-pacman"
#>
param(
    [string]$FeatureDir = (Join-Path (Get-Location) 'specs\001-modern-powerups-pacman')
)

$scriptPath = $MyInvocation.MyCommand.Path
$generatorRel = '.specify/scripts/powershell/generate-spec-filled.ps1'

$specPath = Resolve-Path (Join-Path $FeatureDir 'spec.md') -ErrorAction SilentlyContinue
if (-not $specPath) {
    Write-Error "spec.md not found in feature directory: $FeatureDir"
    exit 1
}
$specPath = $specPath.Path
$filledPath = Join-Path (Split-Path $specPath -Parent) 'spec_filled.md'

try {
    $content = Get-Content -Path $specPath -Raw -ErrorAction Stop
} catch {
    Write-Error ("Failed to read {0}: {1}" -f $specPath, $_)
    exit 1
}

$timestamp = (Get-Date).ToString('yyyy-MM-dd HH:mm:ss')
$header = "> **Generated snapshot:** This file is auto-generated from `spec.md` by `$generatorRel` on $timestamp. Do not edit this file directly.`n`n"

try {
    Set-Content -Path $filledPath -Value ($header + $content) -Encoding UTF8 -ErrorAction Stop
    Write-Host "Generated: $filledPath"
} catch {
    Write-Error ("Failed to write {0}: {1}" -f $filledPath, $_)
    exit 1
}
